name: 'S3 Static Site Deploy'
description: 'S3 wrapper to install AWS CLI and sync build folder to S3 bucket'
inputs:
  buildDir: 
    description: 'Build directory to deploy to s3. Ex: build, dist...'
    required: false
    default: 'build'
runs:
  using: 'node16'
  main: 'dist/index.js'
